[package]
name = "identity_access"
version = "0.1.0"
authors = ["rhuffus <rafahernandeznovillo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common"}
actix = "0.8"
uuid = "0.7.4"
